Added a MQTTv5 version of the pub + sub tcp python script.
emqx/MQTT-Client-Examples pull request #58
Opened 2022-10-31 23:04 UTC by lucas-emqx

2022-11-01 16:01 UTC, zibuyu1995 requested changes

2022-11-01 16:01 UTC, zibuyu1995 commented on mqtt-client-Python3/pub_sub_tcp_v5.py
> +        if result.is_published():
It is not useful for QoS 0, because the Broker does not reply to the ACK, you can test it.

2022-11-01 17:44 UTC, lucas-emqx commented on mqtt-client-Python3/pub_sub_tcp_v5.py
> +BROKER = '127.0.0.1'
I based myself off of https://github.com/emqx/MQTT-Client-Examples/blob/master/mqtt-client-Python3/pub_tcp_v5.py

Should we change pub_tcp_v5.py to broker.emqx.io as well?

2022-11-02 01:15 UTC, Zhiw approved these changes

2022-11-02 01:24 UTC, zibuyu1995 commented on mqtt-client-Python3/pub_sub_tcp_v5.py
> +BROKER = '127.0.0.1'
Yes, please modify together.

2022-11-02 06:51 UTC, zibuyu1995 approved these changes

2022-11-02 06:52 UTC, merged