feat(python): support auto reconnect
emqx/MQTT-Client-Examples pull request #84
Opened 2023-04-24 01:55 UTC by Catgok

python 自动重连

2023-04-25 15:03 UTC, zibuyu1995 requested changes
建议用 pylint 检查一下代码

2023-04-27 07:22 UTC, Catgok commented on mqtt-client-Python3/pub_sub_tcp.py
> +                     .format(reconnect_delay=reconnect_delay))
已修改

2023-04-28 03:25 UTC, zibuyu1995 approved these changes

2023-05-04 01:21 UTC, Zhiw commented
Please resolve the conflict first

2023-05-04 03:11 UTC, Catgok commented
resolved the conflict

2023-05-08 01:40 UTC, Zhiw approved these changes

2023-05-08 01:55 UTC, wuzufeng commented on mqtt-client-Python3/pub_ws.py
> +
多了一个空行

2023-05-08 05:44 UTC, Adek06 approved these changes

2023-05-09 01:31 UTC, merged